[package]
name = "delete-characters-to-make-fancy-string"
version = "0.1.0"
authors = ["pr0found <runqiang.crq@alibaba-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
